# Generated by Django 2.2.7 on 2019-11-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20191111_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
